name: Tugas-15-fix-gatau-kapan-selesai

on:
  push:
    branches: [ "main" ]

jobs:
  
  build-stage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create Artifact
        run: |
          mkdir dist
          echo "<h1>Deploy Otomatis Berhasil!</h1><p>Update pada: $(date)</p>" > dist/index.html

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-content
          path: dist/

  
  deploy-stage:
    runs-on: ubuntu-latest
    needs: build-stage
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: web-content
          path: deploy-folder

      - name: Transfer to VPS via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "deploy-folder/*"
          target: "/root/tugas-15"
          strip_components: 1

      - name: Finalize & Check via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            echo "Mengecek isi folder /root/tugas-15..."
            ls -la /root/tugas-15
