name: Automasi Keamanan Tugas 13
on:
  push:
    branches: [ "main" ] 

jobs:
  eksekusi-keamanan:
    runs-on: ubuntu-latest
    steps:
      - name: Ambil Kode
        uses: actions/checkout@v4

      - name: Verifikasi Secret Masking
        env:
          KUNCI_SAYA: ${{ secrets.MY_SECRET_KEY }}
        run: |
          echo "Memulai proses validasi..."
          echo "Isi variabel rahasia adalah: $KUNCI_SAYA"
